demouiza/build.gradle
sample/build.gradle
samplelivestream/build.gradle
sampletv/build.gradle
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideoService.java

update logic mini player

---

uizacoresdk/build.gradle

- Try to archives `mux` library beside `uizacoresdk`

[Improvement] Archives mux library

---

uizabase/src/main/java/vn/uiza/core/common/Constants.java
uizabase/src/main/java/vn/uiza/core/utilities/LAnimationUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LDateUtils.java
uizabase/src/main/java/vn/uiza/core/utilities/LDeviceUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LSMSUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LScreenUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LSocialUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LStoreUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/LUIUtil.java
uizabase/src/main/java/vn/uiza/core/utilities/statusbar/StatusBarCompatKitKat.java
uizabase/src/main/java/vn/uiza/core/utilities/statusbar/StatusBarCompatLollipop.java
uizabase/src/main/java/vn/uiza/utils/util/Encryptor.java
uizabase/src/main/java/vn/uiza/utils/util/FileUtils.java
uizabase/src/main/java/vn/uiza/utils/util/IntentUtils.java
uizabase/src/main/java/vn/uiza/utils/util/ShellUtils.java
uizacoresdk/src/main/java/uizacoresdk/util/Loitp.java
uizacoresdk/src/main/java/uizacoresdk/util/UZData.java
uizacoresdk/src/main/java/uizacoresdk/util/UZTrackingUtil.java
uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java
uizalivestream/src/main/res/values/strings.xml

-  Move some common hardcode values to constant file
- Optimize some String values
**Impacted area**
- None
**Ticket URL**
- https://uizaio.atlassian.net/browse/EBC-124

[Task-124][Improvement] Move some common hardcode values to constant file

---

uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

- [HotFix] Re-added missing find views `ivLiveView`, `ivLiveTime`

[HotFix] Re-added missing find views

---

uizacoresdk/src/main/java/uizacoresdk/util/TmpParamData.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideo.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZPlayerManager.java

Fix view_rebuffer_duration, view_time_to_first_frame to ms not timestamp
**Ticket URL**
https://uizaio.atlassian.net/browse/EBC-327
https://uizaio.atlassian.net/browse/EBC-328

[Fix] view_rebuffer_duration, view_time_to_first_frame to ms from master

---

CHANGELOG.md
README.md

Update document ver 4.0.8 after refactor source code

Update document ver 4.0.8

---

uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

Ref: https://uizaio.atlassian.net/browse/UB-217

[Fix UB-217] Không tiếp tục casting sau khi replay video

---

uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

Ref: https://uizaio.atlassian.net/browse/UB-218

[Fix UB-218] Các option Subtitle, Quality setting, Mute bị biến mất khi Casting

---

uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

Ref: https://uizaio.atlassian.net/browse/UB-213

[Fix UB-213] Hiển thị sai tổng thời gian của video

---

uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java

Ref: https://uizaio.atlassian.net/browse/UB-215

[Fix UB-215] Crash khi click setting button ở chế độ Full Screen

---

uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java

Ref: https://uizaio.atlassian.net/browse/UB-214

[Fix UB-214] Radio button tại các options bị mất sau khi đổi màn hình từ Full screen sang small screen

---

uizacoresdk/src/main/java/uizacoresdk/chromecast/CastyPlayer.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

Fix UB-229: Không thể thay đổi thời lượng trên thanh thời lượng khi đang casting
https://uizaio.atlassian.net/browse/UB-229
Fix UB-236: Không tự động rotate màn hình sau khi home app trong chế độ casting
https://uizaio.atlassian.net/browse/UB-236
Fix UB-217: Không tiếp tục casting sau khi replay video
https://uizaio.atlassian.net/browse/UB-217

Fix UB-229, UB-236, UB-217

---

uizalivestream/src/main/java/uizalivestream/model/PresetLiveStreamingFeed.java
uizalivestream/src/main/java/uizalivestream/view/RtmpCameraHelper.java
uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java

fixed livestream in android lower

fixed best bitrate

---

uizalivestream/src/main/java/uizalivestream/model/PresetLiveStreamingFeed.java
uizalivestream/src/main/java/uizalivestream/view/RtmpCameraHelper.java
uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java

Fixed livestream in android lower

fixed live stream

---

uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java

- Correct call for prepare audio function
**Impacted Area**
- Livestream audio bitrate

[Fix] Correct call for prepare audio function

---

sample/src/main/java/testlibuiza/app/LSApplication.java
sample/src/main/java/testlibuiza/sample/v3/linkplay/PlayerActivity.java
sample/src/main/res/layout/player_activity.xml
samplelivestream/src/main/java/test/loitp/samplelivestream/App.java
uizabase/src/main/java/vn/uiza/core/utilities/LDateUtils.java
uizabase/src/main/java/vn/uiza/restapi/uiza/UZService.java
uizabase/src/main/java/vn/uiza/restapi/uiza/model/UTCTime.java
uizacoresdk/src/main/java/uizacoresdk/util/UZData.java
uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZPlayerManager.java

- Calculate HLS Latency on developer mode
- NOTE:
- In case user seek the `seekbar` time to previous which over the current playing `segment` duration, skip to calculate the latency.
- Currently the latency value is:
` long latency = Frame_Displayed_Time - EXT_X_PROGRAM_DATE_TIME` 
(both value are based on `UTC` time).
**Impacted Area**
- None
**Ticket URL**
- https://uizaio.atlassian.net/browse/EBC-386

[Task] Calculate HLS Latency on developer mode

---

uizabase/build.gradle
uizabase/src/main/res/values/attrs.xml
uizacoresdk/build.gradle
uizalivestream/build.gradle

- fixed compile error sendo seller app
- upgrade min sdk
- revert res removed

Fixed compile error with sendo seller app

---

uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZNoAdsPlayerManager.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZPlayerManager.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZPlayerManagerAbs.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideo.java

- Fix Dependencies for FUZPlayerManager

Fix Dependencies for FUZPlayerManager

---

uizalivestream/build.gradle

- The issue & fix references:
- https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/294
- https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/eb3c1acfe3ff54cac628511ee6ac07f1b2dec7e7#diff-09914b152f6c7df32d455660da3a308eR771

Upgrade RTP Lib for issue 294

---

uizabase/build.gradle
uizacoresdk/build.gradle

[Update] Increase version of Glide to 4.9.0

[Update] Increase version of Glide

---

sample/src/main/java/testlibuiza/sample/v3/linkplay/PlayerActivity.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

- Support seek to live edge while livestreaming feature.

[Improvement] Support seek to live edge while livestreaming feature

---

uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java

-  Prevent exception when try to resume livestream after come back from background

[Improvement] Prevent exception when try to resume livestream after come back from background

---

demouiza/src/main/java/uiza/v4/live/LivestreamBroadcasterActivity.java
sample/src/main/java/testlibuiza/app/LSApplication.java
sample/src/main/java/testlibuiza/sample/livestream/LivestreamBroadcasterActivity.java
sample/src/main/java/testlibuiza/sample/v3/uzv3/SetEntityIdActivity.java
sample/src/main/java/testlibuiza/sample/v3/uzv3/UZPlayerActivity.java
samplelivestream/src/main/java/test/loitp/samplelivestream/App.java
uizabase/src/main/java/vn/uiza/core/common/Constants.java
uizabase/src/main/java/vn/uiza/utils/UZUtilBase.java
uizabase/src/test/java/vn/uiza/utils/UZUtilBaseTest.java
uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java
uizalivestream/src/main/java/uizalivestream/view/UZLivestream.java

- Currently, we still can not play a livestream video, so add function `initLiveEntity` for playing livestream video kind
- Update `sample` modules

[Fix] Play a livestream video

---

uizalivestream/src/main/java/uizalivestream/view/RtmpCameraHelper.java

Remove max bitrate

---

uizalivestream/src/main/java/uizalivestream/view/RtmpCameraHelper.java

remove maxbitrate

---

sample/src/main/java/testlibuiza/app/LSApplication.java
uizabase/src/main/java/vn/uiza/restapi/uiza/UZService.java
uizabase/src/main/java/vn/uiza/restapi/uiza/model/v2/listallentity/Subtitle.java
uizabase/src/main/java/vn/uiza/restapi/uiza/model/v4/subtitle/ResultGetSubtitles.java
uizabase/src/test/java/vn/uiza/restapi/uiza/UZServiceTest.java
uizabase/src/test/resources/api-responses/video/getSubtitles_success.json
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/IUZPlayerManager.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

- Implements to get & show video's subtitle(s)
**Impacted Area**
- Video Player
**Ticket URL**
- https://uizaio.atlassian.net/browse/EBC-429

[Task] Implements to get & show video's subtitle(s)

---

sample/src/main/java/testlibuiza/app/LSApplication.java
sample/src/main/java/testlibuiza/sample/v3/fb/FBVideoActivity.java
uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideoService.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java
uizacoresdk/src/main/res/layout/float_uiza_video.xml

- Flexible showPiP function with or without button `exo_picture_in_picture`

[Fix] Flexible showPiP function

---

sample/src/main/java/testlibuiza/sample/v3/event/EventActivity.java
uizacoresdk/src/main/java/uizacoresdk/interfaces/UZLiveContentCallback.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java

- Do not show some SDK text on views or dialogs

[Update] Do not show some SDK text on views or dialogs

---

sample/src/main/java/testlibuiza/sample/v3/fb/FBVideoActivity.java
sample/src/main/res/layout/layout_floating_controls_skin.xml
uizabase/src/main/java/vn/uiza/core/common/Constants.java
uizabase/src/main/res/values/ids.xml
uizacoresdk/src/main/java/uizacoresdk/util/UZUtil.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideo.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZVideoService.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/UZVideo.java
uizacoresdk/src/main/res/layout/layout_floating_controls.xml
uizacoresdk/src/main/res/layout/layout_floating_uiza_video.xml

- Allows custom PiP control buttons `PlayPause, Fullscreen & Exit`

[Improvement] Flexible set pip controls skin

---

demouiza/src/main/java/uiza/v4/helper/view/UizaActionBar.java
demouiza/src/main/res/layout/frm_home.xml
demouiza/src/main/res/layout/frm_search.xml
demouiza/src/main/res/layout/uiza_action_bar.xml
demouiza/src/main/res/layout/uiza_home_activity.xml
demouiza/src/main/res/layout/uiza_ima_video_activity_rl_slide.xml
demouiza/src/main/res/layout/uiza_option_activity.xml
demouiza/src/main/res/layout/uiza_player_activity.xml
demouiza/src/main/res/layout/uiza_search_activity.xml
demouiza/src/main/res/layout/uiza_splash_activity.xml
demouiza/src/main/res/layout/v3_frm_home.xml
demouiza/src/main/res/layout/v3_frm_login.xml
demouiza/src/main/res/layout/v3_frm_search.xml
demouiza/src/main/res/layout/v3_uiza_ima_video_activity_rl_slide.xml
demouiza/src/main/res/layout/v3_uiza_splash_activity.xml
demouiza/src/main/res/layout/v4_frm_login.xml
demouiza/src/main/res/layout/v4_home_canslide_activity.xml
sampletv/src/main/res/layout/activity_main.xml
uizabase/src/main/res/values/attrs.xml

- Remove `RealtimeBlurView` from sample apps

[Fix] Remove RealtimeBlurView from sample apps

---

sample/src/main/java/testlibuiza/app/LSApplication.java
uizabase/src/main/java/vn/uiza/core/common/Constants.java
uizacoresdk/src/main/java/uizacoresdk/view/floatview/FUZPlayerManagerAbs.java
uizacoresdk/src/main/java/uizacoresdk/view/rl/video/IUZPlayerManager.java

-  Support SRT subtitle format

[Improvement] Support SRT subtitle format

---

README.md
configs/checkstyle/uiza_check.xml
configs/codestyle/uiza_style.xml

- Add code format & check style rules. We will use:
- [Google Java Code Style](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml)
- [Google Java Check Style](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)
Note: The indentation config of the codestyle is changed:
Java: 
```
<indentOptions>
<option name="INDENT_SIZE" value="4" />
<option name="CONTINUATION_INDENT_SIZE" value="8" />
<option name="TAB_SIZE" value="4" />
</indentOptions>
```
XML:
```
<indentOptions>
<option name="INDENT_SIZE" value="4" />
<option name="CONTINUATION_INDENT_SIZE" value="4" />
<option name="TAB_SIZE" value="4" />
</indentOptions>
```

[Improvement] Add code format & check style rules
